name: Build JAR

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/libs/*.jar